### ISSUE TITLE
When node is not setup, pages requiring the node connection should be disabled

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#11]
Currently, even if the bee node is not setup correctly yet, users can navigate to pages like peers or accounting and see pretty much blank pages. The easiest thing to do is to disable these pages.
![Screenshot 2021-03-10 at 17 11 02](https://user-images.githubusercontent.com/7974813/110663855-24c07600-81c7-11eb-9fc7-7794c3356403.png)

**Comment by matmertz25** [comment]
See https://github.com/ethersphere/bee-status/pull/1/commits/901c6a403f655e09c21e5f2643a0cd2b0902ef4c for fix

**Comment by matmertz25** [comment]
resolved in #1 

Now shows user an empty component with the ability to redirect to the status checks page or other troubleshooting resources

![image](https://user-images.githubusercontent.com/40722304/111003904-02109780-8356-11eb-98d1-ef9dfcc4da01.png)
