### ISSUE TITLE
Peers should not be removable

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#12]
![Screenshot 2021-03-10 at 17 37 30](https://user-images.githubusercontent.com/7974813/110664022-576a6e80-81c7-11eb-8cbd-405f97da9773.png)

**Comment by matmertz25** [comment]
Im unclear why we wouldnt want support this functionality as the API provides an interface for it.  I agree that we wouldn't want people accidentally clearing out peers for no reason but also would like to give as much control and functionality to the user to manage / monitor their nodes. 

Perhaps we can in the future have an "advanced/developer" toggle in the settings or something to hide or display advanced functionalities so we can provide maximum control  over the node to operator.

**Comment by matmertz25** [comment]
Removed for now https://github.com/ethersphere/bee-status/pull/1/commits/d0099c0006243c6afdda856765ae63796cae8c9b.
