### ISSUE TITLE
Format balance numbers

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#13]
The balance numbers should

- [x] use monospace font
- [x] be aligned to the right
- [x] have same number of digits
- [x] should not use scientific notation
- [x] have separators (whitespace for each thousand(th) )
- [x] mention units (BZZ or gBZZ)

**Comment by matmertz25** [comment]
added several of these improvements in the latest pull request with the exception of right alignment of all the numbers in certain areas to accommodate display of absolute 0
