### ISSUE TITLE
Show API and debug API status in the left navigation

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#16]
**Rationale**
Pretty much all the pages require connection to the API of the bee node and many to the debug API. However, except for the status page, it is unclear whether the connection is working.

**Task**
Display the connection to bee API and debug API in the bottom left corner or some other appropriate place

**Comment by matmertz25** [comment]
https://github.com/ethersphere/bee-status/pull/1/commits/8bb43ddeded3033a22db79fa210a13093361c6d1

![image](https://user-images.githubusercontent.com/40722304/110869435-75ec6a80-8298-11eb-9c47-162813fdbc22.png)

**Comment by matmertz25** [comment]
resolved in #1
