### ISSUE TITLE
Node API check should not be part of first check

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#19]
With the latest changes to the debug API (not yet released), some endpoints now start even if all the conditions are not met (unlike the node API). The Node API check should probably be one of the last as it needs pretty much all the previous steps to start.

**Comment by matmertz25** [comment]
See commit https://github.com/ethersphere/bee-status/pull/30/commits/5e7c22d475b0dca02e8b3a2cb4c003c2009f3160 in #30
