### ISSUE TITLE
Node ID should be changed to Swarm Overlay Address

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#20]
It also probably is not all that interesting information for most users and should probably be accompanied with other information like ETH address, PSS key etc.

![Screenshot 2021-03-10 at 17 02 06](https://user-images.githubusercontent.com/7974813/110690363-251b3a00-81e4-11eb-9dd1-4fa42fd79e58.png)

**Comment by matmertz25** [comment]
Updated wording and added other relevant information for context a4cc73128682320a66aa173ae454a67a652b85e4.

**Comment by matmertz25** [comment]
resolved in #1
