### ISSUE TITLE
Add Multi OS support for Troubleshooting commands

### ISSUE THREAD

**Issue by matmertz25** [ethersphere/bee-status#4]
Description:
The UI has code blocks defined for troubleshooting node setup. These code blocks should support multiple OS types

**Comment by matmertz25** [comment]
Added in f3299ac

**Comment by vojtechsimetka** [comment]
This looks good! Having #10 would be nice

**Comment by matmertz25** [comment]
https://github.com/ethersphere/bee-status/pull/1/commits/e6b0cea1a3321f7ae4f236093643b732b86e3b82. Added localhost detection. Would like to have the actual node report the OS though as it really should be something coming from the node itself so that this application can support remote connections.

**Comment by matmertz25** [comment]
Closing as the basic functionality is fulfilled. #10 expands upon further refinement
