### ISSUE TITLE
Node setup page should be accessible even when everything is green

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#7]
Currently, once the node is setup properly, the Node Setup details disappears and only status data are shown. Ideally both should always be visible.

![Screenshot 2021-03-10 at 17 02 06](https://user-images.githubusercontent.com/7974813/110659249-b2e62d80-81c2-11eb-947b-d3cf25f60b72.png)
![Screenshot 2021-03-10 at 17 02 22](https://user-images.githubusercontent.com/7974813/110659259-b5488780-81c2-11eb-99c8-c50f1898c4ef.png)

**Comment by matmertz25** [comment]
Fixed in https://github.com/ethersphere/bee-status/pull/1/commits/e20c0b45d13945c31ab8fb82e8fb15d90e355489.  Added "View Status Checks" button on status page to toggle between the checks and the regular healthy node page.

**Comment by matmertz25** [comment]
resolved in #1
