### ISSUE TITLE
Setup should not be expanded by default

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#8]
Having a bunch of details displayed by default can be intimidating.

- [x] Users should expand it at their own leisure.
- [x] There should be an indicator these steps are clickable. Maybe expand button?
- [x] The labels should be aligned to left
- [x] Clicking on the step number should also be possible (right now only the label is clickable)

![Screenshot 2021-03-10 at 17 11 02](https://user-images.githubusercontent.com/7974813/110660298-b332f880-81c3-11eb-82c8-a3ef0b519653.png)

**Comment by matmertz25** [comment]
![image](https://user-images.githubusercontent.com/40722304/110863871-513fc500-828f-11eb-852f-ddfdd817cc37.png)
