### ISSUE TITLE
Automatically detect OS for the troubleshooting tabs

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#9]
The screenshot below is opened on `macOS` and hence the `macOS` tab should be selected
![Screenshot 2021-03-10 at 17 14 05](https://user-images.githubusercontent.com/7974813/110660693-17ee5300-81c4-11eb-8747-2c07fff61e99.png)

**Comment by matmertz25** [comment]
resolved in #1. Would like to make this more robust in the future by adding an actual agent from the health API to support remote node OS detection rather than always defaulting to the localhost client
